#!/bin/bash

. /opt/helpers

export SOLIDMATTER_JUKEBOX_URL=${SOLIDMATTER_JUKEBOX_URL:-jukebox.solidmatter}
export SOLIDMATTER_JUKEBOX_BACKEND_URL=${SOLIDMATTER_JUKEBOX_BACKEND_URL:-backend.jukebox.solidmatter}

export DEFAULT_MYSQL_HOST=${DEFAULT_MYSQL_HOST:-localhost}
export DEFAULT_MYSQL_PORT=${DEFAULT_MYSQL_PORT:-3306}
export DEFAULT_MYSQL_USER=${DEFAULT_MYSQL_USER:-solidmatter}
export DEFAULT_MYSQL_PASS=${DEFAULT_MYSQL_PASS:-solidmatter}

export SOLIDMATTER_MYSQL_USER=${SOLIDMATTER_MYSQL_USER:-solidmatter}
export SOLIDMATTER_MYSQL_PASS=${SOLIDMATTER_MYSQL_PASS:-solidmatter}
export SOLIDMATTER_MYSQL_DATABASE=${SOLIDMATTER_MYSQL_DATABASE:-solidmatter}

# run setup scripts
run-parts --lsbsysinit --exit-on-error -- /opt/setup

cat <<-END
Starting Supervisor ...
END

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
trap "supervisorctl shtutdown && wait" SIGTERM
wait
