#!/bin/bash

. /opt/helpers

echo "=> mariadb: setup"

chown -R mysql:mysql /var/lib/mysql

if [ ! "$(ls -A /var/lib/mysql)" ]; then
	echo "=> mariadb: datadir is empty ... initializing"
	/usr/bin/mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
fi

#chown -R mysql:mysql /var/run/mysqld

/etc/init.d/mysql start
helper_mysql_wait localhost 3306
