#!/bin/bash

. /opt/helpers

echo "=> setup mariadb"

chown -R mysql:mysql /var/lib/mysql
chown -R mysql:mysql /var/log/mysql

if [ ! "$(ls -A /var/lib/mysql)" ]; then
	echo "=> MySQL datadir is empty ... initializing"
	/usb/bin/mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
fi

#chown -R mysql:mysql /var/run/mysqld

/etc/init.d/mysql start
helper_mysql_wait localhost 3306
