#!/bin/bash

. /opt/helpers

echo "=> setup solidmatter"

mkdir /var/log/solidmatter
chown www-data: /var/log/solidmatter

# modify solidmatter apache site config
sed -i -e "s#@JUKEBOX_URL@#${SOLIDMATTER_JUKEBOX_URL}#g" /etc/apache2/sites-available/solidmatter.conf
sed -i -e "s#@JUKEBOX_BACKEND_URL@#${SOLIDMATTER_JUKEBOX_BACKEND_URL}#g" /etc/apache2/sites-available/solidmatter.conf

# Enable apache solidmatter mod.
a2ensite solidmatter



#helper_mysql_root << END
mysql << EOF
    CREATE DATABASE IF NOT EXISTS ${SOLIDMATTER_MYSQL_DATABASE};
    GRANT ALL
      ON ${SOLIDMATTER_MYSQL_DATABASE}.*
      TO '${SOLIDMATTER_MYSQL_USER}'@'localhost'
      IDENTIFIED BY '${SOLIDMATTER_MYSQL_PASS}';
EOF

mysql < /var/www/solidmatter/solidmatter.sql

# modify solidmatter interface config
sed -i -e "s#@JUKEBOX_URL@#${SOLIDMATTER_JUKEBOX_URL}#g" /etc/solidmatter/interface.xml
sed -i -e "s#@JUKEBOX_BACKEND_URL@#${SOLIDMATTER_JUKEBOX_BACKEND_URL}#g" /etc/solidmatter/interface.xml
